# Flatten JSON format different methods using Python!

src: https://medium.com/@rganesh0203/flatten-json-format-different-methods-using-python-1d4357e446cd

In [3]:
import pandas as pd

# Example JSON data
data = {
    "id": 1,
    "name": "John Doe",
    "address": {
        "street": "123 Main St",
        "city": "Anytown"
    },
    "phones": [
        {"type": "home", "number": "123-456-7890"},
        {"type": "work", "number": "987-654-3210"}
    ]
}

df = pd.json_normalize(data)
df

,id,name,phones,address.street,address.city
0,1,John Doe,"[{'type': 'home', 'number': '123-456-7890'}, {...",123 Main St,Anytown

# Method 2: Using Recursive Function

In [5]:
def flatten_json(y):
    out = {}

    def flatten(x, name=''):
        if isinstance(x, dict):
            for a in x:
                flatten(x[a], name + a + '_')
        elif isinstance(x, list):
            for i, a in enumerate(x):
                flatten(a, name + str(i) + '_')
        else:
            out[name[:-1]] = x

    flatten(y)
    return out

# Example JSON data
data = {
    "id": 1,
    "name": "John Doe",
    "address": {
        "street": "123 Main St",
        "city": "Anytown"
    },
    "phones": [
        {"type": "home", "number": "123-456-7890"},
        {"type": "work", "number": "987-654-3210"}
    ]
}

# Flatten JSON data
flat_data = flatten_json(data)
df = pd.json_normalize(flat_data)
df

,id,name,address_street,address_city,phones_0_type,phones_0_number,phones_1_type,phones_1_number
0,1,John Doe,123 Main St,Anytown,home,123-456-7890,work,987-654-3210

# Method 3: Using Third-Party Library

In [6]:
!pip install flatten_json

Collecting flatten_json
  Downloading flatten_json-0.1.14-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from flatten_json) (1.17.0)
Downloading flatten_json-0.1.14-py3-none-any.whl (8.0 kB)
Installing collected packages: flatten_json
Successfully installed flatten_json-0.1.14

In [7]:
from flatten_json import flatten

In [8]:
# Example JSON data
data = {
    "id": 1,
    "name": "John Doe",
    "address": {
        "street": "123 Main St",
        "city": "Anytown"
    },
    "phones": [
        {"type": "home", "number": "123-456-7890"},
        {"type": "work", "number": "987-654-3210"}
    ]
}
# Flatten JSON data
flat_data = flatten_json(data)
df = pd.json_normalize(flat_data)
df

,id,name,address_street,address_city,phones_0_type,phones_0_number,phones_1_type,phones_1_number
0,1,John Doe,123 Main St,Anytown,home,123-456-7890,work,987-654-3210

# Method 4: Using json and itertools.chain for Custom Flattening

In [ ]:
import json
from itertools import chain

In [9]:
# Example JSON data
data = {
    "id": 1,
    "name": "John Doe",
    "address": {
        "street": "123 Main St",
        "city": "Anytown"
    },
    "phones": [
        {"type": "home", "number": "123-456-7890"},
        {"type": "work", "number": "987-654-3210"}
    ]
}
# Custom function to flatten JSON
def flatten_json_custom(d, parent_key='', sep='_'):
    items = []
    for k, v in d.items():
        new_key = f"{parent_key}{sep}{k}" if parent_key else k
        if isinstance(v, dict):
            items.extend(flatten_json_custom(v, new_key, sep=sep).items())
        elif isinstance(v, list):
            for i, item in enumerate(v):
                items.extend(flatten_json_custom({f"{new_key}_{i}": item}, '', sep=sep).items())
        else:
            items.append((new_key, v))
    return dict(items)
# Flatten JSON data
flat_data = flatten_json_custom(data)
# print(flat_data)
df = pd.json_normalize(flat_data)
df

,id,name,address_street,address_city,phones_0_type,phones_0_number,phones_1_type,phones_1_number
0,1,John Doe,123 Main St,Anytown,home,123-456-7890,work,987-654-3210

# Method 5: Using pd.json_normalize from Pandas

In [10]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [11]:
import pandas as pd

# Example JSON data
data = {
    "id": 1,
    "name": "John Doe",
    "address": {
        "street": "123 Main St",
        "city": "Anytown"
    },
    "phones": [
        {"type": "home", "number": "123-456-7890"},
        {"type": "work", "number": "987-654-3210"}
    ]
}

# Flatten JSON data
df = pd.json_normalize(data)
df

,id,name,phones,address.street,address.city
0,1,John Doe,"[{'type': 'home', 'number': '123-456-7890'}, {...",123 Main St,Anytown

# Method 6: Handling Nested JSON Arrays

In [13]:
import pandas as pd

# Example JSON data with nested dictionaries and an array of objects
data = {
    "id": 1,
    "name": "John Doe",
    "address": {
        "street": "123 Main St",
        "city": "Anytown"
    },
    "phones": [
        {"type": "home", "number": "123-456-7890"},
        {"type": "work", "number": "987-654-3210"}
    ]
}

# Use pandas.json_normalize to flatten the nested JSON
df = pd.json_normalize(
    data,

    # 🟦 'phones' is the key that contains a list of objects (array of dicts).
    # Each object in the array will become a separate row in the resulting DataFrame.
    record_path='phones',

    # 🟨 These are fields outside the array, but we want to include them in each row.
    # They are pulled from the parent level of the JSON and repeated for each phone.
    meta=[
        'id',                 # Add the root-level 'id' to each row
        'name',               # Add the root-level 'name' to each row
        ['address', 'street'],# Add 'street' from nested 'address' dictionary
        ['address', 'city']   # Add 'city' from nested 'address' dictionary
    ]
)

# Display the flattened DataFrame
df

   type        number id      name address.street address.city
0  home  123-456-7890  1  John Doe    123 Main St      Anytown
1  work  987-654-3210  1  John Doe    123 Main St      Anytown

# Method 7: Handling Deeply Nested JSON

In [14]:
import pandas as pd

# 📦 Example JSON data with:
# - Root-level fields: id, name
# - Nested object: address
# - Deeper nested object: address.geo
# - Array of objects: phones
data = {
    "id": 1,
    "name": "John Doe",
    "address": {
        "street": "123 Main St",
        "city": "Anytown",
        "geo": {
            "lat": "40.7128",
            "long": "74.0060"
        }
    },
    "phones": [
        {"type": "home", "number": "123-456-7890"},
        {"type": "work", "number": "987-654-3210"}
    ]
}

# 🧰 Use pd.json_normalize() to flatten:
# - phones list (each item becomes a row)
# - include values from parent and deeply nested fields
df = pd.json_normalize(
    data,

    # 🔹 This is the list of dictionaries we want to explode into rows
    record_path='phones',

    # 🔸 These are the fields we want to pull in from higher levels
    meta=[
        'id',                     # from root level
        'name',                   # from root level
        ['address', 'street'],    # from nested address dict
        ['address', 'city'],      # from nested address dict
        ['address', 'geo', 'lat'],# from deeper nested geo inside address
        ['address', 'geo', 'long']# from deeper nested geo inside address
    ]
)

# 📄 View the resulting flattened DataFrame
df

,type,number,id,name,address.street,address.city,address.geo.lat,address.geo.long
0,home,123-456-7890,1,John Doe,123 Main St,Anytown,40.7128,74.0060
1,work,987-654-3210,1,John Doe,123 Main St,Anytown,40.7128,74.0060

# Method 8: PySpark

In [15]:
!pip install pyspark

Requirement already satisfied: pyspark in /usr/local/lib/python3.11/dist-packages (3.5.1)
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.11/dist-packages (from pyspark) (0.10.9.7)

In [ ]:
# # Initialize Spark session
# spark = SparkSession.builder \
#     .appName("Flatten JSON") \
#     .getOrCreate()
# # Load JSON data into DataFrame
# df = spark.read.json("data.json")
# # Display the schema of the DataFrame
# df.printSchema()
# # Flatten the DataFrame
# df_flat = df.withColumn("phones", explode(col("phones"))) \
#     .select(
#         col("id"),
#         col("name"),
#         col("address.street").alias("address_street"),
#         col("address.city").alias("address_city"),
#         col("phones.type").alias("phone_type"),
#         col("phones.number").alias("phone_number")
#     )
# # Show the flattened DataFrame
# df_flat.display()
# # Stop the Spark session

In [16]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import explode, col
import json

# 🟢 Step 1: Create a Spark session
spark = SparkSession.builder \
    .appName("Flatten JSON") \
    .getOrCreate()

# 🟢 Step 2: Define your nested JSON data as a Python dictionary
data = {
    "id": 1,
    "name": "John Doe",
    "address": {
        "street": "123 Main St",
        "city": "Anytown"
    },
    "phones": [
        {"type": "home", "number": "123-456-7890"},
        {"type": "work", "number": "987-654-3210"}
    ]
}

# 🔸 Convert dictionary to JSON string (so Spark can understand it)
json_str = json.dumps(data)

# 🔸 Parallelize into an RDD (list of one JSON string), then read as a DataFrame
df = spark.read.json(spark.sparkContext.parallelize([json_str]))

# 🟢 Step 3: Display the schema (structure) of the nested JSON
df.printSchema()

# Example schema output:
# root
#  |-- address: struct (nullable = true)
#  |    |-- city: string (nullable = true)
#  |    |-- street: string (nullable = true)
#  |-- id: long (nullable = true)
#  |-- name: string (nullable = true)
#  |-- phones: array (nullable = true)
#  |    |-- element: struct
#  |    |    |-- number: string (nullable = true)
#  |    |    |-- type: string (nullable = true)

# 🟢 Step 4: Flatten the array of objects in 'phones' using explode()
df_flat = df.withColumn("phones", explode(col("phones"))) \
    .select(
        col("id"),                                 # keep root-level id
        col("name"),                               # keep root-level name
        col("address.street").alias("address_street"),  # flatten nested address.street
        col("address.city").alias("address_city"),      # flatten nested address.city
        col("phones.type").alias("phone_type"),         # flatten exploded phone type
        col("phones.number").alias("phone_number")      # flatten exploded phone number
    )

# 🟢 Step 5: Show the flattened DataFrame as a table
df_flat.show(truncate=False)

# Example Output:
# +---+--------+--------------+----------+----------+--------------+
# |id |name    |address_street|address_city|phone_type|phone_number|
# +---+--------+--------------+-------------+----------+-------------+
# |1  |John Doe|123 Main St   |Anytown     |home      |123-456-7890 |
# |1  |John Doe|123 Main St   |Anytown     |work      |987-654-3210 |
# +---+--------+--------------+-------------+----------+-------------+

# 🛑 Step 6: Stop the Spark session
spark.stop()

root
 |-- address: struct (nullable = true)
 |    |-- city: string (nullable = true)
 |    |-- street: string (nullable = true)
 |-- id: long (nullable = true)
 |-- name: string (nullable = true)
 |-- phones: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- number: string (nullable = true)
 |    |    |-- type: string (nullable = true)

+---+--------+--------------+------------+----------+------------+
|id |name    |address_street|address_city|phone_type|phone_number|
+---+--------+--------------+------------+----------+------------+
|1  |John Doe|123 Main St   |Anytown     |home      |123-456-7890|
|1  |John Doe|123 Main St   |Anytown     |work      |987-654-3210|
+---+--------+--------------+------------+----------+------------+

### Handling More Complex Nested JSON

In [20]:
# 📦 Import required PySpark classes
from pyspark.sql import SparkSession
from pyspark.sql.functions import explode, col
import json

# ✅ Step 1: Define and save nested JSON
data = {
    "id": 1,
    "name": "John Doe",
    "address": {
        "street": "123 Main St",
        "city": "Anytown",
        "geo": {
            "lat": "40.7128",
            "long": "74.0060"
        }
    },
    "phones": [
        {"type": "home", "number": "123-456-7890"},
        {"type": "work", "number": "987-654-3210"}
    ]
}

# ✅ Step 2: Save data to file — must be a list for Spark to read as records
with open('data_complex.json', 'w') as f:
    json.dump([data], f)  # <-- Wrap in a list for valid JSON Lines format

# ✅ Step 3: Start Spark session
spark = SparkSession.builder \
    .appName("Flatten JSON") \
    .getOrCreate()

# ✅ Step 4: Load JSON data (should be a JSON file with an array of objects)
df = spark.read.json("data_complex.json")

# ✅ Step 5: Flatten the JSON step-by-step
df_flat = df.withColumn("phones", explode(col("phones"))) \
    .select(
        col("id"),
        col("name"),
        col("address.street").alias("address_street"),
        col("address.city").alias("address_city"),
        col("address.geo.lat").alias("address_geo_lat"),
        col("address.geo.long").alias("address_geo_long"),
        col("phones.type").alias("phone_type"),
        col("phones.number").alias("phone_number")
    )

# ✅ Step 6: Show flattened result
df_flat.show(truncate=False)

# ✅ Step 7: Stop Spark session
spark.stop()

+---+--------+--------------+------------+---------------+----------------+----------+------------+
|id |name    |address_street|address_city|address_geo_lat|address_geo_long|phone_type|phone_number|
+---+--------+--------------+------------+---------------+----------------+----------+------------+
|1  |John Doe|123 Main St   |Anytown     |40.7128        |74.0060         |home      |123-456-7890|
|1  |John Doe|123 Main St   |Anytown     |40.7128        |74.0060         |work      |987-654-3210|
+---+--------+--------------+------------+---------------+----------------+----------+------------+

# Method 9: SQL

### Using PostgreSQL

```
-- Example table with JSON data
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    data JSONB
);

INSERT INTO users (data) VALUES
('{"name": "John Doe", "address": {"street": "123 Main St", "city": "Anytown"}, "phones": [{"type": "home", "number": "123-456-7890"}, {"type": "work", "number": "987-654-3210"}]}');
```

Flatten

```
SELECT
    id,
    data->>'name' AS name,
    data->'address'->>'street' AS address_street,
    data->'address'->>'city' AS address_city,
    phone.value->>'type' AS phone_type,
    phone.value->>'number' AS phone_number
FROM
    users,
    jsonb_array_elements(data->'phones') AS phone;
```

### MySQL

```
-- Example table with JSON data
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    data JSON
);

INSERT INTO users (data) VALUES
('{"name": "John Doe", "address": {"street": "123 Main St", "city": "Anytown"}, "phones": [{"type": "home", "number": "123-456-7890"}, {"type": "work", "number": "987-654-3210"}]}');

SELECT
    id,
    JSON_UNQUOTE(JSON_EXTRACT(data, '$.name')) AS name,
    JSON_UNQUOTE(JSON_EXTRACT(data, '$.address.street')) AS address_street,
    JSON_UNQUOTE(JSON_EXTRACT(data, '$.address.city')) AS address_city,
    JSON_UNQUOTE(JSON_EXTRACT(phones, '$.type')) AS phone_type,
    JSON_UNQUOTE(JSON_EXTRACT(phones, '$.number')) AS phone_number
FROM
    users,
    JSON_TABLE(data->'$.phones', '$[*]' COLUMNS (
        phone_type VARCHAR(10) PATH '$.type',
        phone_number VARCHAR(20) PATH '$.number'
    )) AS phones;
```

# Method 10 : Spark SQL

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import explode, col

spark = SparkSession.builder \
    .appName("Flatten JSON with Spark SQL") \
    .getOrCreate()

Create data.json

```
{
    "id": 1,
    "name": "John Doe",
    "address": {
        "street": "123 Main St",
        "city": "Anytown"
    },
    "phones": [
        {"type": "home", "number": "123-456-7890"},
        {"type": "work", "number": "987-654-3210"}
    ]
}
```

In [ ]:
# Assuming the JSON data is stored in a file named 'data.json'
df = spark.read.json("data.json")

# Display the schema of the DataFrame
df.printSchema()

In [ ]:
# Flatten the DataFrame
df_flat = df.withColumn("phone", explode(col("phones"))) \
    .select(
        col("id"),
        col("name"),
        col("address.street").alias("address_street"),
        col("address.city").alias("address_city"),
        col("phone.type").alias("phone_type"),
        col("phone.number").alias("phone_number")
    )

# Show the flattened DataFrame
df_flat.display()

### Handling More Complex Nested JSON


```
{
    "id": 1,
    "name": "John Doe",
    "address": {
        "street": "123 Main St",
        "city": "Anytown",
        "geo": {
            "lat": "40.7128",
            "long": "74.0060"
        }
    },
    "phones": [
        {"type": "home", "number": "123-456-7890"},
        {"type": "work", "number": "987-654-3210"}
    ]
}
```

In [ ]:
# Load JSON data into DataFrame
df = spark.read.json("data_complex.json")
# Flatten the DataFrame step by step
df_flat = df.withColumn("phone", explode(col("phones"))) \
    .select(
        col("id"),
        col("name"),
        col("address.street").alias("address_street"),
        col("address.city").alias("address_city"),
        col("address.geo.lat").alias("address_geo_lat"),
        col("address.geo.long").alias("address_geo_long"),
        col("phone.type").alias("phone_type"),
        col("phone.number").alias("phone_number")
    )
# Show the flattened DataFrame
df_flat.display()